services:
  api:
    build: .
    container_name: middleware_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  tests:
    build: .
    container_name: middleware_tests
    volumes:
      - .:/app
    command: pytest -v